Update django_ecr_eks.yaml

diff --git a/.github/workflows/django_ecr_eks.yaml b/.github/workflows/django_ecr_eks.yaml
--- a/.github/workflows/django_ecr_eks.yaml
+++ b/.github/workflows/django_ecr_eks.yaml
@@ -6,17 +6,38 @@ name: Deploy Django app to EKS
 on:
   workflow_dispatch:
 jobs:
-  build:
+  Setup_EKS:
     runs-on: ubuntu-latest
     env:
       AWS_DEFAULT_REGION: ap-south-1
       AWS_REGION: ap-south-1
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-
     steps:
       - name: Checkout terraform code
         uses: actions/checkout@v3
+      - name: Install Terraform
+        uses: hashicorp/setup-terraform@v1
+        with:
+          terraform_version: 1.4.2
+      - name: Initialize Terraform
+        working-directory: aws/eks/
+        run: terraform init
+      - name: Plan the configuration
+        working-directory: aws/eks/
+        run: terraform plan
+      - name: Apply Terraform
+        working-directory: eks/
+        run: terraform apply -auto-approve
+  Build_and_push :
+    needs: Setup_EKS
+    runs-on: ubuntu-latest
+    env:
+      AWS_DEFAULT_REGION: ap-south-1
+      AWS_REGION: ap-south-1
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+    steps:
       - name: Checkout django app code
         uses: actions/checkout@v3
         with:
@@ -24,8 +45,17 @@ jobs:
       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1
-        
+      - name: Install AWS CLI
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y python3-pip
+          sudo pip3 install awscli
+      - name: Check EKS cluster
+        run: |
+          aws eks describe-cluster --region ${{ secrets.AWS_REGION }} --name EKS01-Cluster || echo "EKS cluster not found"
+        id: eks-cluster-check
       - name: Build and push django image to ECR
+        if: steps.eks-cluster-check.outcome == 'success'
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           ECR_REPOSITORY: demo_ecr_django
@@ -33,18 +63,5 @@ jobs:
         run: |
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
-#       - name: Install Terraform
-#         uses: hashicorp/setup-terraform@v1
-#         with:
-#           terraform_version: 1.4.2
-#       - name: Initialize Terraform
-#         working-directory: aws/eks/
-#         run: terraform init
-#       - name: Plan the configuration
-#         working-directory: aws/eks/
-#         run: terraform plan
-      #- name: Apply Terraform
-      #  working-directory: eks/
-      #  run: terraform apply -auto-approve
 
       
